name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Bump commit_number.md and push
        run: |
          FILE="commit_number.md"
          if [ ! -f "$FILE" ]; then
            echo "Hello, my name is bishwa shah" > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            n=$(grep -oP 'commit number: \K\d+' "$FILE" || true)
            n=${n:-0}
            sed -i "s/^commit number: .*/commit number: $((n+1))/" "$FILE"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "Update commit number" || true

          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ajinkyagh/DailyCommits.git" HEAD:main
