name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create file and commit
        run: |
          FILE="commit_number.md"
          if [ ! -f "$FILE" ]; then
            echo "Hello, my name is bishwa shah" > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE" || true)
            CURRENT_COUNT=${CURRENT_COUNT:-0}
            NEXT_COUNT=$((CURRENT_COUNT + 1))
            sed -i "/^commit number:/c\commit number: $NEXT_COUNT" "$FILE"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "Update commit number" || echo "No changes to commit"

          # Ensure remote is correct (overwrites any bad https://https:// value)
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ajinkyagh/DailyCommits.git"
          git remote -v

          # Push to the branch (change 'main' if your default branch is different)
          git push origin HEAD:main
